Spelling: Various fixes
dialect-app/dialect pull request #181
Opened 2021-05-22 15:51 UTC by comradekingu

2021-05-22 16:00 UTC, rafaelmardojai commented on data/resources/window.ui
> +                                    <property name="tooltip-text" translatable="yes">⮂</property>
It's a tooltip text and should be descriptive with the action of the button.

2021-05-22 16:34 UTC, rafaelmardojai requested changes

2021-05-22 16:34 UTC, rafaelmardojai commented on data/resources/window.ui
> +                                    <property name="tooltip-text" translatable="yes">⮂</property>
It's a tooltip text and should be descriptive with the action of the button.

2021-05-22 17:17 UTC, comradekingu commented on data/resources/window.ui
> +                                    <property name="tooltip-text" translatable="yes">⮂</property>
```suggestion
                                    <property name="tooltip-text" translatable="yes">Switches the languages</property>
```

2021-05-23 04:53 UTC, fushinari requested changes
Thanks for working on this! Strings are often a very tricky matter because they should convey to the user exactly what clicking a button will do but sometimes it's not that simple. It's especially troublesome with neither of us being native English speakers.

Just going to note a few of my concerns with the changes, please comment or make changes accordingly and we can get to merging this.. :smile:

2021-05-23 04:53 UTC, fushinari commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Use "Auto" as the default language every time the program is started</property>
This is too long. It should be 55 characters or less.

2021-05-23 04:53 UTC, fushinari commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Use Google for speech synthesis functionality.</property>
Maybe make this "text-to-speech" instead. Text-to-speech is a more common usage than speech synthesis, so I'd rather keep using the term.

2021-05-23 04:53 UTC, fushinari commented on data/resources/preferences.ui
> +            <property name="description" translatable="yes">The GNOME search provider in Dialect is turned off when Live translation is to reduce API abuse. Ensure it is also turned on in the GNOME S
To avoid confusion, maybe make this "In order to reduce API abuse, Dialect's GNOME search provider is turned off when Live Translation is. Ensure that the search provider is also turned on in GNOME Settings." ?

2021-05-23 04:53 UTC, fushinari commented on data/resources/window.ui
> +                            <property name="label" translatable="yes">Connect to the Internet first.</property>
Probably better to leave this as is. We don't want to tell the user what to do, we only want to tell the user why the application isn't functioning as it should.

2021-05-23 04:53 UTC, fushinari commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Enter a translation service URL.</property>
Maybe "Enter URL for translation service"? I mean, it has a default fallback value, so "Enter a translation service URL" doesn't seem right for some reason.

2021-05-23 04:53 UTC, fushinari commented on data/resources/window.ui
> +                                    <property name="tooltip-text" translatable="yes">Switches the languages</property>
Tooltips are not for what a button does, it's for a button will do. So, maybe better to leave it be.

2021-05-24 12:31 UTC, Vistaus commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Use "Auto" as the default language every time the program is started</property>
Just a suggestion: maybe just shorten it to ‘Use “Auto” as the default language’? That should be clear enough for the majority of English speakers.

2021-05-24 12:35 UTC, Vistaus commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Enter a translation service URL.</property>
Or, alternatively, ‘Enter the URL of a translation service’?

2021-05-25 04:05 UTC, fushinari commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Use "Auto" as the default language every time the program is started</property>
Yep, that should be fine!

2021-05-25 04:09 UTC, fushinari commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Enter a translation service URL.</property>
Maybe. I'm not so sure because all versions feels wrong in my head for some reason :sweat_smile: .

2021-05-25 04:37 UTC, comradekingu commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Enter a translation service URL.</property>
@fushinari Including: "Enter a link to a translation service"?

2021-05-25 04:39 UTC, fushinari commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Enter a translation service URL.</property>
Address feels more appropriate

2021-05-27 10:08 UTC, fushinari commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Enter a translation service URL.</property>
"Enter address of the translation service" was what I originally had in mind, but string length was the issue. Any string that's roughly the same length as the original or less should be fine

2021-05-27 21:37 UTC, comradekingu commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Use "Auto" as the default language every time the program is started</property>
```suggestion
                <property name="subtitle" translatable="yes">Use "Auto" as the default language</property>
```

2021-05-27 21:39 UTC, comradekingu commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Use Google for speech synthesis functionality.</property>
I thought this was the description, which doesn't actually do much over saying it 3 times if it is just "text-to-speech".

2021-05-27 21:40 UTC, comradekingu commented on data/resources/preferences.ui
> +            <property name="description" translatable="yes">The GNOME search provider in Dialect is turned off when Live translation is to reduce API abuse. Ensure it is also turned on in the GNOME S
What exactly does turning on a search provider in the GNOME settings entail?

2021-05-27 21:41 UTC, comradekingu commented on data/resources/preferences.ui
> +            <property name="description" translatable="yes">The GNOME search provider in Dialect is turned off when Live translation is to reduce API abuse. Ensure it is also turned on in the GNOME S
```suggestion
            <property name="description" translatable="yes">To reduce API abuse, the GNOME search provider in Dialect is turned off when Live translation is. Ensure the search provider is also turned on in the GNOME Settings.</property>
```

2021-05-27 21:42 UTC, comradekingu commented on data/resources/window.ui
> +                                    <property name="tooltip-text" translatable="yes">Switches the languages</property>
```suggestion
                                    <property name="tooltip-text" translatable="yes">Switch languages</property>
```

2021-05-27 21:43 UTC, comradekingu commented on data/resources/window.ui
> +                            <property name="label" translatable="yes">Connect to the Internet first.</property>
One is not as obvious a conclusion based on available info.

2021-05-27 21:54 UTC, rafaelmardojai commented on data/resources/preferences.ui
> +            <property name="description" translatable="yes">The GNOME search provider in Dialect is turned off when Live translation is to reduce API abuse. Ensure it is also turned on in the GNOME S
You aren't going to get results from that provider on the GNOME shell search.

We added that line because depending on some factors (like if the app is installed through flatpak or directly on the host), the search provider can be disabled by default on GNOME search settings.

2021-05-28 04:38 UTC, fushinari commented on data/resources/window.ui
> +                            <property name="label" translatable="yes">Connect to the Internet first.</property>
We want to leave this error as generalized as possible because it could be due to a variety of reasons. The user could actually be connected to the internet for all we know. So it's better to say something like the app not being able to detect a network connection. There may be better wording for it, but we don't want to tell the user to connect to the internet instead.

2021-05-28 04:42 UTC, fushinari commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Use Google for speech synthesis functionality.</property>
It doesn't matter how many times we say the same thing because the information that we really want to convey in the description is that Google will be used. A bit of repetition for the sake of completeness is fine here imo.

@rafaelmardojai what do you think?

2021-05-28 15:05 UTC, comradekingu commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Use Google for speech synthesis functionality.</property>
It does matter, because it is redundant.
The original should be text-to-speech, so an error is avoided too.

2021-05-28 15:06 UTC, comradekingu commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Use Google for speech synthesis functionality.</property>
```suggestion
                <property name="subtitle" translatable="yes">Use Google for TTS.</property>
```

2021-05-28 15:07 UTC, comradekingu commented on data/resources/window.ui
> +                            <property name="label" translatable="yes">Connect to the Internet first.</property>
```suggestion
                            <property name="label" translatable="yes">No network connection detected.</property>
```

2021-05-28 15:09 UTC, comradekingu commented on data/resources/window.ui
> +                            <property name="label" translatable="yes">Connect to the Internet first.</property>
That there could be an error in the detection or routing for this specifically is not usually the case. Not a whole lot more correct, but harder to decipher.

2021-05-28 15:13 UTC, comradekingu commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Enter a translation service URL.</property>
Lets revisit this when and if an alternative can be presented within those limits.
The original has a marked noun error, where it should be "the URL", and "a translation service", but that makes it too long. The alternative works.

2021-05-28 15:17 UTC, rafaelmardojai commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Use Google for speech synthesis functionality.</property>
The new version `Use Google for TTS.` looks good to me.

2021-05-28 15:22 UTC, fushinari commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Use Google for speech synthesis functionality.</property>
Yeah, that looks good to me too. Could you also fix the title? Like you mentioned, hyphenation is needed (which was why i said "make this text-to-speech" rather than ask to revert but I now realize I wasn't able to say clearly, goes to show how lacking my language skills are :sweat_smile:)

2021-05-28 15:22 UTC, fushinari commented on data/resources/preferences.ui
> +                <property name="subtitle" translatable="yes">Enter a translation service URL.</property>
Okay, that's good enough for now I guess.

2021-05-28 15:54 UTC, fushinari approved these changes
Looks great!

2021-05-28 15:54 UTC, fushinari commented on data/resources/preferences.ui
>                  <property name="title" translatable="yes">Text to Speech</property>
```suggestion
                <property name="title" translatable="yes">Text-to-Speech</property>
```

2021-05-28 16:16 UTC, rafaelmardojai commented on data/resources/preferences.ui
>                  <property name="title" translatable="yes">Text to Speech</property>
What's wrong with this?

2021-05-28 16:44 UTC, fushinari commented on data/resources/preferences.ui
>                  <property name="title" translatable="yes">Text to Speech</property>
Nothing much. Hyphenating it is more correct. It's our bug though. But I was hoping for input when suggesting here

2021-05-28 16:49 UTC, rafaelmardojai commented on data/resources/preferences.ui
>                  <property name="title" translatable="yes">Text to Speech</property>
Right. You can commit the suggestion :P

2021-05-28 16:51 UTC, fushinari commented on data/resources/preferences.ui
>                  <property name="title" translatable="yes">Text to Speech</property>
Yes, but I wanted to confirm this is what we want :)

2021-05-28 16:56 UTC, merged