window: Use `Adw.MultiLayoutView`
dialect-app/dialect pull request #406
Opened 2024-10-09 18:51 UTC by rafaelmardojai

Use  `Adw.MultiLayoutView` for moving widgets around the desktop and mobile modes without duplicating them.

Also remove deprecated widgets like Adw.Squeezer.

2024-10-13 11:16 UTC, mufeedali requested changes
I'm also a bit conflicted on the new bottom button layout. I think it's a change that makes sense though. So only issue I see would be the bottom padding in vertical mode.

2024-10-13 11:16 UTC, mufeedali commented on dialect/style.css
> -  padding-bottom: 0;
This looks weird to me... I think I'd want the padding to remain the same as before :(

2024-10-13 11:17 UTC, mufeedali commented on dialect/style.css
> -  padding-bottom: 0;
![Screenshot From 2024-10-13 16-46-47](https://github.com/user-attachments/assets/9f6d0cb7-b3b8-4016-b74b-9a5cc00b9304)

2024-10-13 13:50 UTC, rafaelmardojai commented on dialect/style.css
> -  padding-bottom: 0;
What about `6px`? Looks more homogeneous imo.
![Captura desde 2024-10-13 08-49-31](https://github.com/user-attachments/assets/be8c604c-c1ae-4d70-8a13-0f9b36f087fd)

2024-10-14 17:32 UTC, mufeedali commented on dialect/style.css
> -  padding-bottom: 0;
I still think 4 looks better, a third opinion would be nice on this :sweat_smile:

2024-10-14 18:19 UTC, rafaelmardojai commented on dialect/style.css
> -  padding-bottom: 0;
My logic is that the toolbar has `6px`, so an extra `6px` equals the translation boxes spacing. 

> a third opinion would be nice on this 😅

I guess we should ask some designer? 😅

2024-10-14 18:23 UTC, mufeedali commented on dialect/style.css
> -  padding-bottom: 0;
The thing is, it feels like too minor of a detail to be obsessed with, especially enough to bother a designer with 😅...

I know that your logic is sound, but 6 just "feels" off by just a tiny bit to my eyes and I can't place why

2024-10-14 18:30 UTC, rafaelmardojai commented on dialect/style.css
> -  padding-bottom: 0;
> I know that your logic is sound, but 6 just "feels" off by just a tiny bit to my eyes and I can't place why

And I feel the same for 4px, it looks a bit smaller than all the other spacing 😅. 

I could accept 0px, since at least I can see an uniform 6px padding around the toolbar, do we agree on that?

2024-10-14 18:33 UTC, mufeedali commented on dialect/style.css
> -  padding-bottom: 0;
Yep, zero looks good and looks uniform too.

Sorry for nitpicking over such a minor detail 😅

2024-10-14 18:38 UTC, rafaelmardojai commented on dialect/style.css
> -  padding-bottom: 0;
No problem, I also agree that the `12 + 6px` spacing looked strange. 😅

2024-10-14 19:13 UTC, mufeedali approved these changes

2024-10-14 19:13 UTC, merged